### ISSUE TITLE
undefined symbol when load plugin

### ISSUE THREAD

**Issue by quinzhi** [BrettDong/clang-tidy-plugin-starter#1]
hi, i compiled this example in clang15.05 from 
https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.5/clang+llvm-15.0.5-powerpc64le-linux-ubuntu-18.04.5.tar.xz :

`export LLVM_DIR=path_to_clang15.05_mention_above`
`export Clang_DIR=path_to_clang15.05_mention_above`
`cmake -B build`
`make`

and i got libClangTidyPlugin.so, then i ran 
`home/test/clang/clang/bin/clang-tidy --load build/libClangTidyPlugin.so`

and it output:
`Error opening 'build/libClangTidyPlugin.so': build/libClangTidyPlugin.so: undefined symbol: _ZTIN5clang4tidy15ClangTidyModuleE
  -load request ignored.
`

did i missed something?

**Comment by BrettDong** [comment]
The symbol `_ZTIN5clang4tidy15ClangTidyModuleE` is type info. Can you try adding the following line to `CMakeLists.txt` and see if it solves the undefined symbol problem:
```cmake
target_compile_options(ClangTidyPlugin PRIVATE -fno-rtti)
```

**Comment by quinzhi** [comment]
> The symbol `_ZTIN5clang4tidy15ClangTidyModuleE` is type info. Can you try adding the following line to `CMakeLists.txt` and see if it solves the undefined symbol problem:
> 
> ```cmake
> target_compile_options(ClangTidyPlugin PRIVATE -fno-rtti)
> ```

Thanks！this works after i recompiled llvm with` -DBUILD_SHARED_LIBS:BOOL=ON`
